const paymentSchema = new mongoose.Schema(
  {
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Booking",
      required: true,
    },

    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    ownerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    amount: {
      type: Number,
      required: true,
    },

    method: {
      type: String,
      enum: ["eSewa", "Khalti"],
      required: true,
    },

    transactionId: {    //stores transactionId generated by payment gateway after payment success
      type: String,
      unique: true,
      index:true,
      sparse: true, // allows pending payments without transactionId
    },

    status: {
      type: String,
      enum: ["pending", "success", "failed"],
      default: "pending",
      index: true
    },

    paidAt: {
      type: Date,
    },

  },
  { timestamps: true },
);


module.exports = mongoose.model("Payment", paymentSchema);
